---

- name: Install EPEL Package
  hosts: ipareplicas
  remote_user: almalinux
  become: true
  tasks:
  - name: Install package epel-release
    yum:
      name: epel-release
      state: present
      #when: ansible_facts['os_family'] == "Alma Linux" and ansible_facts['lsb']['major_release'] | int == '8' 
    tags: task1

  

  - name: Downgrade Alma Linux 8 to OS Ver 8.9 - Update /etc/dnf/vars/releasever
    shell: |
      yum --releasever=8.9 downgrade redhat-release -y
      echo "8.9" > /etc/dnf/vars/releasever
      dnf update -y
      dnf upgrade -y
    register: downgrade_alma8_result
    ignore_errors: True
    tags: task3
  

  - name: Upgrade all packages
    ansible.builtin.dnf:
      name: "*"
      state: latest
    register: upgrade_package_result
    ignore_errors: True
    tags: task7


  - name: Install Standard Packages
    ansible.builtin.dnf:
      name: 
        - htop
        - wget
        - curl
        - git 
        - net-tools
        - nc
        - iptables-services
        - bind
        - bind-utils
      state: latest
    register: install_package_result
    ignore_errors: True 
    tags: task9

  
  - name: Get short hostname
    debug: hostname_short="{{ hostname.split('.')[0] }}"


  - name: Remove IPA Server 127.0.0.1 entry
    ansible.builtin.lineinfile:
      path: /etc/hosts
      regexp: '^127\.0\.0\.1.*\"${hostname}\".*$'
      owner: root
      group: root
      mode: '0644'
      state: absent
    ignore_errors: True
    tags: task12


  - name: Insert IPA Replica Server host entry
    ansible.builtin.lineinfile:
      path: /etc/hosts
      regexp: '^51\.75\.12\.110.*\"\${hostname}\".*$'
      insertafter: '^127\.0\.0\.1.*localhost.*$'
      line: 	51.75.12.110     "${hostname}"   "${hostname -s}"
      owner: root
      group: root
      mode: '0644'
      state: present
      backup: yes
    ignore_errors: True
    tags: task16


  - name: Insert IPA Server host entry
    ansible.builtin.lineinfile:
      dest: /etc/hosts
      line: 51.83.104.217     ${hostname}  ${hostname -s}
      owner: root
      group: root
      mode: '0644'
      state: present
      backup: yes
    ignore_errors: True
    tags: task13


  - name: Start iptables-services
    service:
      name: iptables 
      state: started
      enabled: yes
    ignore_errors: True 
    tags: task15
  

  - name: Allow related and established connections
    ansible.builtin.iptables:
      chain: INPUT
      ctstate: ESTABLISHED,RELATED
      jump: ACCEPT
    ignore_errors: True
    tags: task17
  

  - name: Allow new incoming SYN packets on TCP port 22 (SSH)
    ansible.builtin.iptables:
      chain: INPUT
      protocol: tcp
      destination_port: 22
      ctstate: NEW
      syn: match
      jump: ACCEPT
      comment: Accept new SSH connections.
    ignore_errors: True
    tags: task19

    vars:
      default_policy: "ACCEPT"
      loopback_iface: lo
      #trusted_networks:
      # In AS278 we trust
      #- "132.247.0.0/16"
      #- "132.248.0.0/16"
      #- "192.100.199.0/24"
      #- "192.100.200.0/24"


  - name: Apply default INPUT and OUTPUT policy
    vars:
      default_policy: "ACCEPT"
      loopback_iface: lo
    iptables:
      chain: "{{ item }}"
      policy: "{{ default_policy }}"
    with_items:
    - "INPUT"
    - "OUTPUT"
    ignore_errors: True
    tags: task21
  

  - name: Allow INPUT loopback traffic
    vars:
      default_policy: "ACCEPT"
      loopback_iface: lo
    iptables:
      table: "filter"
      chain: "INPUT"
      in_interface: "{{ loopback_iface }}"
      jump: "ACCEPT"
    ignore_errors: True
    tags: task23
  

  - name: Allow OUTPUT loopback traffic
    vars:
      default_policy: "ACCEPT"
      loopback_iface: lo
    iptables:
      table: "filter"
      chain: "OUTPUT"
      out_interface: "{{ loopback_iface }}"
      jump: "ACCEPT"
    ignore_errors: True
    tags: task25


  - name: Allow ICMP traffic
    iptables:
      table: "filter"
      chain: "INPUT"
      protocol: "icmp"
      jump: "ACCEPT"
    ignore_errors: True
    tags: task29
  
  # - name: Allow traffic from trusted networks
  #   iptables:
  #     table: "filter"
  #     chain: "INPUT"
  #     source: "{{ item }}"
  #     jump: "ACCEPT"
  #   with_items:
  #   - "{{ trusted_networks }}"
  #   ignore_errors: True
  #   tags: task16
  
  - name: Allow traffic on public ports
    iptables:
      table: "filter"
      chain: "INPUT"
      destination_port: "{{ item.port }}"
      protocol: "{{ item.protocol }}"
      state: "{{ item.state }}"
      jump: "ACCEPT"
    with_items:
    - { port: 22,protocol: "tcp" , state: "present"}
    - { port: 80, protocol: "tcp" ,  state: "present"}
    - { port: 443, protocol: "tcp" , state: "present"}
    - { port: 4505, protocol: "tcp" , state: "present"}
    - { port: 4506, protocol: "tcp" , state: "present"}
    - { port: 389, protocol: "tcp" , state: "present"}
    - { port: 636, protocol: "tcp" , state: "present"}
    - { port: 88, protocol: "tcp" , state: "present"}
    - { port: 464, protocol: "tcp" , state: "present"}
    - { port: 789, protocol: "tcp" , state: "present"}
    - { port: 53, protocol: "tcp" , state: "present"}
    - { port: 123, protocol: "tcp" , state: "present"}
    - { port: 7389, protocol: "tcp" , state: "present"}
    - { port: 8443, protocol: "tcp" , state: "present"}
    - { port: 9443, protocol: "tcp" , state: "present"}
    - { port: 9444, protocol: "tcp" , state: "present"}
    - { port: 9445, protocol: "tcp" , state: "present"}
    - { port: 8005, protocol: "tcp" , state: "present"}
    - { port: 8009, protocol: "tcp" , state: "present"}
    ignore_errors: True
    tags: task31
  

  - name: Block INVALID Traffic
    ansible.builtin.iptables:
      chain: INPUT
      ctstate: 'INVALID'
      jump: 'DROP'
      state: 'present'
      table: 'filter'
    ignore_errors: True
    tags: task33


  - name: Reject tcp with tcp-reset
    ansible.builtin.iptables:
      chain: INPUT
      protocol: tcp
      reject_with: tcp-reset
      ip_version: ipv4
    ignore_errors: True
    tags: task35

  
  - name: Block other traffic
    ansible.builtin.iptables:
      table: "filter"
      chain: "INPUT"
      jump: "REJECT"
    ignore_errors: True
    tags: task37
  

  - name: "Drop All Other UmMatched Traffic On INPUT chain"
    ansible.builtin.iptables:
      chain: INPUT
      jump: DROP
    ignore_errors: True
    tags: task39



- name: Playbook to configure server as IPA client
  hosts: ipaclients
  become: true
  tags: task40
  
  roles:
  - role: ipaclient
    state: absent
  
  - role: ipaclient
    state: present  


- name: Playbook to configure IPA Replica Server
  hosts: ipareplicas
  become: true
  tags: task42

  roles:
  
  - role: ipareplica
    state: present  


  
  

